# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM-Omni project
"""Neutral contracts for immutable runtime-ready host weight artifacts."""

from .config import (
    CapacityPolicy,
    HostWeightRuntimeConfig,
    IntegrityPolicy,
    ProductionPolicy,
    RemoteImportPolicy,
    RemoteOnMiss,
    RuntimeMode,
    StorageClass,
    StorageDomainPolicy,
    StorageScope,
    ValidationLevel,
    WaitPolicy,
)
from .errors import FailureCode, HostWeightError, HostWeightFailure, ResolutionAction, ResolutionStage
from .identity import (
    AdaptationIdentity,
    CanonicalJson,
    ComponentIdentity,
    IdentityValidationError,
    ProducerIdentity,
    RuntimeWeightLayout,
    WeightArtifactIdentity,
    WeightRepresentation,
    WeightSourceIdentity,
)
from .inspection import (
    ArtifactInspection,
    ArtifactInventoryEntry,
    ArtifactInventoryState,
    DomainInspection,
    HostWeightInspector,
)
from .lease import HostWeightLease, LeaseProvenance, MappedHostRegion
from .manifest import (
    FileManifestEntry,
    ManifestValidationError,
    PublicationMarker,
    TensorKind,
    TensorManifestEntry,
    WeightManifest,
)
from .outcomes import (
    AttemptResult,
    HostWeightResolution,
    PostLoadPublicationOutcome,
    PostLoadPublicationReport,
    ResolutionAttempt,
    ResolutionOutcome,
    ResolutionReport,
    StoreResult,
    StoreStatus,
)
from .protocols import (
    ArtifactWriter,
    BuildRequest,
    CoordinationScope,
    HostWeightStore,
    LookupPhase,
    ProductionMetadata,
    ProductionSourceMode,
    RemoteArtifactDescriptor,
    RemoteArtifactProvider,
    TensorFileWriter,
    TensorWriteSpec,
    WeightProducer,
    WeightProductionSpec,
    WeightRestorePlan,
    WeightRestorer,
)
from .runtime import HostWeightRuntime

__all__ = [
    "AdaptationIdentity",
    "ArtifactInspection",
    "ArtifactInventoryEntry",
    "ArtifactInventoryState",
    "ArtifactWriter",
    "AttemptResult",
    "BuildRequest",
    "CanonicalJson",
    "CapacityPolicy",
    "ComponentIdentity",
    "CoordinationScope",
    "DomainInspection",
    "FailureCode",
    "FileManifestEntry",
    "HostWeightError",
    "HostWeightFailure",
    "HostWeightLease",
    "HostWeightResolution",
    "HostWeightInspector",
    "HostWeightRuntime",
    "HostWeightRuntimeConfig",
    "HostWeightStore",
    "IdentityValidationError",
    "IntegrityPolicy",
    "LeaseProvenance",
    "LookupPhase",
    "ManifestValidationError",
    "MappedHostRegion",
    "ProducerIdentity",
    "PostLoadPublicationOutcome",
    "PostLoadPublicationReport",
    "ProductionMetadata",
    "ProductionPolicy",
    "ProductionSourceMode",
    "PublicationMarker",
    "RemoteArtifactDescriptor",
    "RemoteArtifactProvider",
    "RemoteImportPolicy",
    "RemoteOnMiss",
    "ResolutionAction",
    "ResolutionAttempt",
    "ResolutionOutcome",
    "ResolutionReport",
    "ResolutionStage",
    "RuntimeMode",
    "RuntimeWeightLayout",
    "StorageClass",
    "StorageDomainPolicy",
    "StorageScope",
    "StoreResult",
    "StoreStatus",
    "TensorFileWriter",
    "TensorKind",
    "TensorManifestEntry",
    "TensorWriteSpec",
    "ValidationLevel",
    "WaitPolicy",
    "WeightArtifactIdentity",
    "WeightManifest",
    "WeightProducer",
    "WeightProductionSpec",
    "WeightRepresentation",
    "WeightRestorePlan",
    "WeightRestorer",
    "WeightSourceIdentity",
]
