name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: # for manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
      - uses: pre-commit/action@v3.0.1
        # Don't run the pytest mark check against everything in the CI
        # for now since a lot of files are still missing them. This check
        # is used to help contributors remember to add the marks when they
        # commit.
        env:
          SKIP: check-test-ci-coverage
